[package]
name = "frederico-diagnostics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints.rust]
unsafe_code = "forbid"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
once_cell = { workspace = true }
